name: Check CR approved

on:
    pull_request_target:
       types: [submitted, edited, dismissed]

jobs:
    check_cr_approved:
         if: ${{ github.event.pull_request.number }}
         uses: MetOffice/growss/.github/workflows/check-cr-approved.yaml@main
